ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
kubernetes_version: "1.23.0"
kubectl_auto_completion_dir: "/etc/bash_completion.d"

kubeadm_masters_init_pod_network_cidr: "10.124.0.0/16"
kubeadm_masters_init_service_cidr: "10.96.0.0/16"
kubeadm_masters_init_etc_data_dir: "/app/etcd"
kubeadm_masters_init_cluster_name: "k8s-envoy"
kubeadm_cri_socket: "/var/run/crio/crio.sock"
kubeadm_cluster_api_hostname: "127.0.0.1"
kubeadm_master_group: "k8s_master"
kubeadm_user: "ubuntu"

haproxy_config_dir: "/etc/haproxy"
loadbalancer_apiserver_port: 8443
kube_apiserver_port: 6443
kube_config: /etc/kubernetes/admin.conf
container_runtime: "crio"
cri_sandbox_image: "k8s.gcr.io/pause:3.5"

containerd_storage_dir: "/app/containerd"
containerd_state_dir: "/run/containerd"
containerd_runc_runtime:
  name: runc
  type: "io.containerd.runc.v2"
  engine: ""
  root: ""
  options:
  systemdCgroup: "true"
containerd_registries:
  "docker.io": "https://registry-1.docker.io"

crio_os: "xUbuntu_20.04"
crio_version: "1.23"
crio_root_dir_path: "/app/crio"

helm_path: /app/helm
helm_version: v3.9.1
helm_url: "https://get.helm.sh"
helm_diff_url: https://github.com/databus23/helm-diff/releases/download/v3.4.2
helm_diff_filename: helm-diff-linux-amd64.tgz

cilium_repo_name: "cilium"
cilium_release_name: "cilium"
cilium_chart_name: "cilium/cilium"
cilium_chart_url: "https://helm.cilium.io/"
cilium_chart_version: "1.11.6"
cilium_image_repo: quay.io/cilium/cilium
cilium_image_tag: v1.11.2
cilium_operator_generic_image_repo: quay.io/cilium/operator-generic
cilium_operator_generic_image_tag: v1.11.2

cilium_namespace: cluster-cilium

cilium_helm_bin_path: "/usr/local/bin/helm"
cilium_helm_repo: "https://helm.cilium.io"

cilium_pod_subnet_cidr: "10.112.0.0/16"

cilium_hubble_enable: false
cilium_monitoring_features: false
cilium_kubeproxy_replace: true
