- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common 
    - gnupg2
    - net-tools

- name: Install containerd
  apt: 
    name: containerd
    state: present
    update_cache: yes

- name: Configure containerd
  blockinfile:
    create: true
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a

- name: Enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Configure IP forwarding and iptables
  blockinfile:
    create: yes
    path: /etc/sysctl.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Persist changes
  command: sysctl -p

- name: Create containerd configuration directory
  file:
    path: /etc/containerd/
    state: directory

- name: Create containerd config file
  template:
    src: "containerd-config.toml.j2"
    dest: "/etc/containerd/config.toml"

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted
    daemon_reload: yes