- name: Configure cri
  blockinfile:
    create: true
    path: "/etc/modules-load.d/{{ container_runtime }}.conf"
    block: |
      overlay
      br_netfilter

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a

- name: Enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Configure IP forwarding and iptables
  blockinfile:
    create: yes
    path: /etc/sysctl.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Persist changes
  command: sysctl -p