- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Installing pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux
    - openshift
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2
    - net-tools