- hosts: all
  become: yes
  vars_files:
    - "./defaults/main.yml"
  tasks:
    - import_tasks: "./tasks/pre-install.yml"
    - import_tasks: "./tasks/containerd-setup.yml"
    - import_tasks: "./tasks/k8s-loadbalancer.yml"
    - import_tasks: "./tasks/k8s-common.yml"

- hosts: k8s_master
  become: yes
  vars_files:
    - "./defaults/main.yml"
  tasks:
    - import_tasks: "./tasks/helm-install.yml"
    - import_tasks: "./tasks/k8s-master.yml"
    - import_tasks: "./tasks/k8s-cni.yml"

- hosts: k8s_worker
  become: yes
  vars_files:
    - "./defaults/main.yml"
  tasks:
    - import_tasks: "./tasks/k8s-node.yml"