- hosts: all
  become: yes
  roles:
    - pre-install
    - loadbalancer
    - cri
    - k8s-common

- hosts: k8s_master
  become: yes
  vars:
    node_role: "master"
  roles:
    - helm
    - k8s-cluster
    - k8s-network

- hosts: k8s_worker
  become: yes
  vars:
    node_role: "worker"
  roles:
    - k8s-cluster
